config/routes.rb
Rails.application.routes.draw do

  get 'scores/show'

  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get  'inquiry'          => 'inquiry#index'
  post 'inquiry/confirm'  => 'inquiry#confirm'
  post 'inquiry/complete' => 'inquiry#complete'

  resources :invites, only: [:new,:create]

  resources :scores
  resources :notes, only: [:create]

  get  'mario' => 'mario#index'
  get  'mario2' => 'mario#index2'

  get '/users'     => 'users#index', as:'users'
  get '/:username' => 'users#show',  as:'user'#!最後に設置

  #only: [:index,:show,:new,:create,:edit,:update,:destroy]
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :owner, :class_name => "User"
  validates :name, presence: true

  has_many :notes, dependent: :destroy
  accepts_nested_attributes_for :notes, allow_destroy: true
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
    @score = Score.find(params[:id])
  end

  def new
    @score = current_user.scores.build
    @score.notes.build
  end

  def create
    @score = current_user.scores.build(score_params)
    if @score.save
      flash[:success] = "Score created!"
      redirect_to edit_score_path(@score.id)
    else
      render new_score_path
    end
  end

  def edit
    @score = Score.find(params[:id])
    #@score.notes.order("id DESC")
    #return render :text => CGI.escapeHTML(@score.notes.inspect).gsub(/,/,'<br>')
  end

  def update
    @score = Score.find(params[:id])
    if @score.update(score_params)
      flash[:success] = "Score edited!"
      redirect_to edit_score_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @score = current_user.scores.find(params[:id])
    @score.destroy
    flash[:success] = "Score deleted!"
    redirect_to root_path
  end

  private
  def score_params
    params.require(:score).permit(:name, notes_attributes: [:id, :score_id, :user_id, :data, :_destroy])
  end
end

app/views/scores/edit.html.erb
<% content_for :title, 'Score' %>
<% content_for :css do %><%= stylesheet_link_tag 'score' %><% end %>
<% content_for :js do %><%= javascript_include_tag 'editScore' %><% end %>

<div id="Score">
<div class="row">
<div class="medium-6 medium-centered columns">

<div class="text-center">
  <div id="Frame"><canvas id="Canvas"></canvas></div>
</div>

<div class="text-center" style="margin-bottom: 1rem;">
  <a href="#" id="ArrowLeft" style="vertical-align: middle;"><i class="fa fa-arrow-circle-o-left fa-lg"></i></a>
  <input type="range" id="Scroll">
  <a href="#" id="ArrowRight" style="vertical-align: middle;"><i class="fa fa-arrow-circle-o-right fa-lg"></i></a>
</div>

<div class="text-center">
  <button type="button" id="Play" class="button radius tiny">Play</button>
  <button type="button" id="Stop" class="button radius tiny">Stop</button>
  <button type="button" id="Clear" class="button radius tiny">Clear</button>
  <button type="button" id="Data" class="button radius tiny">Data</button>
</div>

<% checked_arr = [] %>
<%= form_for(@score) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <!--トラック-->
  <ul>
  <%= f.fields_for :notes, @score.notes.sort_by(&:id) do |notes_fields| %>
  <li style="margin-bottom:0.75rem;font-size:0.75rem;">
    <%= notes_fields.hidden_field :id %>
    <% note_num = notes_fields.options[:child_index]+1 %>
    <% note_user = notes_fields.object.user %>

    <!-- 編集ラジオボタン判定 -->
    <% if !checked_arr.index(note_user.id) && current_user == note_user%>
      <% checked = "checked=checked" %>
      <% checked_arr << note_user.id %>
    <% end %>

    <!--トラック-->
    <strong>Track<%= note_num %></strong>
    <input type="hidden" class="TrackColor" value="<%= note_num %>">
    <!--表示-->
    <label><input type="checkbox" name="show" value="<%= note_num %>" checked="checked" style="vertical-align:0;margin-bottom:0;">表示</label>
    <!--編集-->
    <% if current_user == note_user %>
      <label><input type="radio" <%= checked %> name="track" value="<%= note_num %>" style="vertical-align:0;margin-bottom:0;">編集</label>
    <% else %>
      <label><input type="radio" <%= checked %> name="track" value="<%= note_num %>" style="vertical-align:0;margin-bottom:0;" disabled='disabled'>編集</label>
    <% end %>
    <!--削除-->
    <% if current_user == note_user && note_num != 1 %>
      <label><%= notes_fields.check_box :_destroy, style:'vertical-align:0;margin-bottom:0;' %>削除</label>
    <% else %>
      <label><%= notes_fields.check_box :_destroy, style:'vertical-align:0;margin-bottom:0;', disabled:'disabled' %>削除</label>
    <% end %>
    <!--作成者-->
    <span>created by </span><strong><%= note_user.username %></strong>
    <!--Data-->
    <%= notes_fields.hidden_field :data, id: 'data'+(notes_fields.options[:child_index]+1).to_s %>
  </li>
  <% end %>
  </ul>

  <!--曲名-->
  <%= f.label :name %>
  <% if current_user == @score.owner %>
    <%= f.text_field :name, class: 'radius' %>
  <% else %>
    <%= f.text_field :name, class: 'radius', readonly: 'readonly' %>
  <% end %>

  <!--BPM & 小節-->
  <div class="row">
    <div class="small-1 columns" style="padding:0;text-align:right">
      <label style="font-size:0.75rem;height:1.5rem;line-height:1.5rem">BPM</label>
    </div>
    <div class="small-3 columns" style="padding-left:0.5rem;">
      <input type="number" id="Bpm" value="120" min="30" class="radius" style="padding:0;height:1.5rem;">
    </div>
    <div class="small-1 columns" style="padding:0;text-align:right">
      <label style="font-size:0.75rem;height:1.5rem;line-height:1.5rem">1拍</label>
    </div>
    <div class="small-3 columns" style="padding-left:0.5rem;">
      <select id="Beat" style="padding:0;height:1.5rem;">
      <option value="4">4分音符</option>
      <option value="8" selected>8分音符</option>
      <option value="16">16分音符</option>
      </select>
    </div>
    <div class="small-1 columns" style="padding:0;text-align:right">
      <label style="font-size:0.75rem;height:1.5rem;line-height:1.5rem">小節</label>
    </div>
    <div class="small-3 columns end" style="padding-left:0.5rem;">
      <input type="number" id="Measure" value="4" min="2" class="radius" style="padding:0;height:1.5rem;">
    </div>
  </div>

  <!--送信-->
  <%= f.submit '更新', class: 'button radius expand' %>
  <!--トラック追加-->
  <div class="text-center" style="margin-top:0.5rem"><%= link_to 'トラック追加', notes_path(note: {score_id: @score.id, user_id: current_user.id}), method: :post %></div>

<% end %>

</div>
</div>
</div>

app/views/scores/new.html.erb
<% content_for :title, 'Score' %>

<div id="Score">
<div class="row">
<div class="medium-6 medium-centered columns">

  <%= form_for(@score) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'radius' %>

    <%= f.fields_for :notes do |notes_fields| %>
      <%= notes_fields.hidden_field :score_id, value: @score.id %>
      <%= notes_fields.hidden_field :user_id, value: current_user.id %>
    <% end %>

    <%= f.submit '新規作曲', class: 'button radius expand' %>
  <% end %>

</div>
</div>
</div>

app/views/scores/show.html.erb
<% content_for :title, @score.name %>
<% content_for :css do %><%= stylesheet_link_tag 'score' %><% end %>
<% content_for :js do %><%= javascript_include_tag 'showScore' %><% end %>


<div id="Score">
<div class="row">
<div class="medium-6 medium-centered columns">

  <h2><%= @score.name %></h2>

  <div id="Frame"><canvas id="Canvas"></canvas></div>

  <div class="text-center" style="margin-bottom:0.75rem;">
    <a href="#" id="ArrowLeft" style="vertical-align: middle;"><i class="fa fa-arrow-circle-o-left fa-lg"></i></a>
    <input type="range" id="Scroll">
    <a href="#" id="ArrowRight" style="vertical-align: middle;"><i class="fa fa-arrow-circle-o-right fa-lg"></i></a>
  </div>

  <div class="text-center" style="margin-bottom:0.75rem;">
    <button type="button" id="Play" class="button radius tiny" style="margin-bottom:0;">Play</button>
    <button type="button" id="Stop" class="button radius tiny" style="margin-bottom:0;">Stop</button>
  </div>

  <ul>
    <% @score.notes.order('id').each_with_index do |note, i| %>
    <li style="margin-bottom:0.75rem;font-size:0.75rem;">
      <strong>Track<%= i+1 %></strong>
      <label><input type="checkbox" name="show" value="<%= i+1 %>" checked="checked" style="vertical-align:0;margin-bottom:0;">演奏</label>
      <span>created by </span><strong><%= note.user.username %></strong>
    </li>
    <input type="hidden" class="TrackColor" value="<%= i+1 %>">
    <input type="hidden" id="data<%= i+1 %>" value="<%= note.data %>">
    <% end %>
  </ul>

  <div class="text-center" style="margin-bottom:0.75rem;">
    <%= link_to "https://twitter.com/intent/tweet?text=#{@score.name}｜&url=#{score_url(@score)}",target:"_blank" do %><i class="fa fa-twitter-square fa-lg" style="color:#fff;"><span class="text-small">ツイート</span></i><% end %>
    <%= link_to "http://www.facebook.com/sharer.php?u=#{score_url(@score)}",target:"_blank" do %><i class="fa fa-facebook-square fa-lg" style="color:#fff;"><span class="text-small">シェア</span></i><% end %>
  </div>

  <div class="text-center" style="margin-bottom:0.75rem;">
    <% if user_signed_in? %>
      <span class="text-small"><%= link_to '共同編集', edit_score_path(@score) %></span>
    <% end %>
    <% if current_user == @score.owner %>
      <span class="text-small"><%= link_to '削除', @score, method: :delete, data: { confirm: '本当に削除しますか？' } %></span>
    <% end %>
  </div>

</div>
</div>
</div>