config/routes.rb
Rails.application.routes.draw do

  get 'scores/show'

  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get  'inquiry'          => 'inquiry#index'
  post 'inquiry/confirm'  => 'inquiry#confirm'
  post 'inquiry/complete' => 'inquiry#complete'

  resources :invites, only: [:new,:create]

  resources :scores
  resources :notes, only: [:create]

  get  'mario' => 'mario#index'
  get  'mario2' => 'mario#index2'

  get '/users'     => 'users#index', as:'users'
  get '/:username' => 'users#show',  as:'user'#!最後に設置

  #only: [:index,:show,:new,:create,:edit,:update,:destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @scores = Score.all.order("updated_at DESC")
  end

end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <% content_for :title, 'Home' %>
  <div id="Home">
  <div class="row">
  <div class="medium-6 medium-centered columns">
    <h1>Home</h1>
    <% if @scores.any? %>
      <ul>
      <% @scores.each do |score| %>
        <li>
          <h2><%= link_to score.name, score_path(score) %></h2>
          <p>
            <span class="text-small"><%= link_to '共同編集', edit_score_path(score) %></span>
            <% if current_user == score.owner %>
              <span class="text-small"><%= link_to '削除', score, method: :delete, data: { confirm: '本当に削除しますか？' } %></span>
            <% end %>
          </p>
          <p><span class="text-small">created by </span><strong><%= link_to score.owner.username, user_path(score.owner.username) %></strong></p>
          <p>
            <% score.notes.each do |collaborators| %>
              <% if collaborators.user.present? && score.owner != collaborators.user %>
                <span class="text-small">collaborators</span>
                <strong><%= link_to collaborators.user.username, user_path(collaborators.user.username) %></strong>
              <% end %>
            <% end %>
          </p>
        </li>
      <% end %>
      </ul>
    <% end %>
  </div>
  </div>
  </div>
<% else %>
  <div id="Top">
  <div class="row">
  <div class="medium-6 medium-centered columns">
    <h1>ONLINE<br>シンプル作曲サービス<!--Your song, everywhere.--></h1>
    <p style="margin:0 auto;padding:0.5rem;width:20rem;font-size:0.75rem;border-top:1px solid #fff;border-bottom:1px solid #fff;">α版のため限定公開中。</p>

<div style="margin-top:20px;text-align:left;" id="Score">

  <h2>Twinkle Twinkle Little Star</h2>
  <div id="Frame"><canvas id="Canvas"></canvas></div>

  <div class="text-center" style="margin-bottom:0.75rem;">
    <a href="#" id="ArrowLeft" style="vertical-align: middle;"><i class="fa fa-arrow-circle-o-left fa-lg"></i></a>
    <input type="range" id="Scroll">
    <a href="#" id="ArrowRight" style="vertical-align: middle;"><i class="fa fa-arrow-circle-o-right fa-lg"></i></a>
  </div>

  <div class="text-center" style="margin-bottom:0.75rem;">
    <button type="button" id="Play" class="button radius tiny" style="margin-bottom:0;">Play</button>
    <button type="button" id="Stop" class="button radius tiny" style="margin-bottom:0;">Stop</button>
  </div>

  <ul style="font-size:0.75rem;">
    <li>
      <strong>Track1</strong>
      <label><input type="checkbox" name="show" value="1" checked="checked" style="vertical-align:0;margin-bottom:0;">演奏</label>
      <span>created by </span><strong>Takahiro</strong>
    </li>
    <input type="hidden" class="TrackColor" value="1">
    <input type="hidden" id="data1" value="{&quot;note&quot;:[[20],[],[20],[],[16],[],[16],[],[15],[],[15],[],[16],[],[],[],[17],[],[17],[],[18],[],[18],[],[19],[],[19],[],[20],[],[],[],[16],[],[16],[],[17],[],[17],[],[18],[],[18],[],[19],[],[],[],[16],[],[16],[],[17],[],[17],[],[18],[],[18],[],[19],[],[],[],[20],[],[20],[],[16],[],[16],[],[15],[],[15],[],[16],[],[],[],[17],[],[17],[],[18],[],[18],[],[19],[],[19],[],[20],[],[],[]],&quot;bpm&quot;:100,&quot;beat&quot;:8,&quot;len&quot;:96}">
    <li>
      <strong>Track2</strong>
      <label><input type="checkbox" name="show" value="2" checked="checked" style="vertical-align:0;margin-bottom:0;">演奏</label>
      <span>created by </span><strong>Takahiro</strong>
    </li>
    <input type="hidden" class="TrackColor" value="2">
    <input type="hidden" id="data2" value="{&quot;note&quot;:[[13],[9],[11],[9],[13],[9],[11],[9],[13],[10],[13],[10],[9,11],[],[],[],[10,15],[13],[10,15],[13],[11,16],[13],[11,16],[13],[12,14],[16],[12],[14],[13,18],[],[],[],[18],[9],[18],[9],[19],[9],[19],[9],[20],[9],[20],[9],[21],[],[],[],[],[9,13],[],[9,13],[],[9,13],[],[9,13],[],[9,13],[],[9,13],[12,14],[],[],[],[18],[20],[18],[20],[18],[18],[18],[18],[17],[17],[17],[17],[9,18],[],[],[],[15],[17],[15],[14],[13],[16],[13],[],[12,16],[],[12,16],[],[13,18],[],[],[]],&quot;bpm&quot;:100,&quot;beat&quot;:8,&quot;len&quot;:96}">
  </ul>

  <% content_for :css do %><%= stylesheet_link_tag 'score' %><% end %>
  <% content_for :js do %><%= javascript_include_tag 'showScore' %><% end %>
</div>

  </div>
  </div>
  </div>
<% end %>