config/routes.rb
Rails.application.routes.draw do

  get 'scores/show'

  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get  'inquiry'          => 'inquiry#index'
  post 'inquiry/confirm'  => 'inquiry#confirm'
  post 'inquiry/complete' => 'inquiry#complete'

  resources :invites, only: [:new,:create]

  resources :scores
  resources :notes, only: [:create]

  get  'mario' => 'mario#index'
  get  'mario2' => 'mario#index2'

  get '/users'     => 'users#index', as:'users'
  get '/:username' => 'users#show',  as:'user'#!最後に設置

  #only: [:index,:show,:new,:create,:edit,:update,:destroy]
end

app/models/inquiry.rb
class Inquiry
  #DBと繋がらないモデルとしている
  include ActiveModel::Model
  #Formで使用するプロパティを定義する
  attr_accessor :name, :email, :message
  
  validates :name, :presence => {:message => '名前を入力してください。'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください。'}
  validates :message, :presence => {:message => 'お問い合わせ内容を記載して下さい。'}
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController

  def index
    @inquiry = Inquiry.new
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def complete
    @inquiry = Inquiry.new(inquiry_params)
    SendMailer.inquiry_email(@inquiry).deliver_now
    flash[:notice] = "お問い合わせありがとうございました。"
    redirect_to root_path
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end

end

app/views/inquiry/confirm.html.erb
<% content_for :title, 'お問い合わせ' %>

<div id="Setting">
<div class="row">
<div class="medium-6 medium-centered columns">

  <h4>この内容でよろしいですか？</h4>
  <%= form_for @inquiry, :url => inquiry_complete_path do |f| %>
    <%= f.text_field :name, class: 'radius', value:@inquiry.name %>
    <%= f.email_field :email, class: 'radius', value:@inquiry.email %>
    <%= f.text_area :message, rows: 10, class: 'radius', value:@inquiry.message %>
    <%= f.submit "送信", class: 'button radius expand' %>
  <% end %>

</div>
</div>
</div>

app/views/inquiry/index.html.erb
<% content_for :title, 'お問い合わせ' %>

<div id="Setting">
<div class="row">
<div class="medium-6 medium-centered columns">

  <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_field :name, class: 'radius', placeholder: '名前' %>
    <%= f.email_field :email, class: 'radius', placeholder: 'メールアドレス' %>
    <%= f.text_area :message, rows: 10, class: 'radius', placeholder: 'お問い合わせ内容' %>
    <%= f.submit "確認", class: 'button radius expand' %>

  <% end %>

</div>
</div>
</div>