config/routes.rb
Rails.application.routes.draw do

  get 'scores/show'

  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get  'inquiry'          => 'inquiry#index'
  post 'inquiry/confirm'  => 'inquiry#confirm'
  post 'inquiry/complete' => 'inquiry#complete'

  resources :invites, only: [:new,:create]

  resources :scores
  resources :notes, only: [:create]

  get  'mario' => 'mario#index'
  get  'mario2' => 'mario#index2'

  get '/users'     => 'users#index', as:'users'
  get '/:username' => 'users#show',  as:'user'#!最後に設置

  #only: [:index,:show,:new,:create,:edit,:update,:destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <%= csrf_meta_tags %>
  <title><%= content_for?(:title) ? yield(:title) + Constants::SERVICE_NAME : Constants::SERVICE_NAME+'ONLINEシンプル作曲サービス' %></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= yield :css %>
</head>
<body>
<div class="off-canvas-wrap" data-offcanvas>
<div class="inner-wrap">

  <!--alert-->
  <%= render 'shared/flash_messages' %>

  <!--navi-->
  <nav class="tab-bar">
    <section class="middle tab-bar-section">
      <h1><%= link_to root_path do %><%= Constants::SERVICE_NAME %><% end %></h1>
    </section>
    <section class="right-small">
      <a class="right-off-canvas-toggle menu-icon" href="#"><span></span></a>
    </section>
  </nav>
  <aside class="right-off-canvas-menu">
    <ul class="off-canvas-list">
      <% if user_signed_in? %>
        <li><%#= link_to current_user.username, user_path(current_user.username) %></li>
        <li><label><%= current_user.username %></label></li>
        <li><%= link_to 'ホーム', root_path %></li>
        <li><%= link_to '新規作曲', new_score_path %></li>
        <li><%= link_to 'プロフィール表示', user_path(current_user.username) %></li>
        <li><%= link_to 'アカウント設定', edit_user_registration_path %></li>
        <li><%= link_to '友達を招待', new_invite_path %></li>
        <li><%= link_to 'フィードバック', "https://twitter.com/intent/tweet?screen_name=takabo_beta",target:"_blank" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: 'delete' %></li>
      <% else %>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
      <% end %>
        <li>
          <div class="icon-bar three-up">
            <a class="item" href="https://twitter.com/takabo_beta" target="target"><i class="fa fa-twitter"></i></a>
            <a class="item" href="http://takabo-beta.hatenablog.com/" target="target"><i class="fa fa-pencil"></i></a>
            <a class="item" href="<%= inquiry_path %>"><i class="fa fa-envelope"></i></a>
          </div>
        </li>
        <li class="copyright">&copy <%= Date.today.year %> <%= Constants::SERVICE_NAME %></li>
    </ul>
  </aside>

  <!--main-->
  <section class="main-section">
    <div id="Main">
    <%= yield %>
    </div>
  </section>

<a class="exit-off-canvas"></a>
</div>
</div>

<%= javascript_include_tag "vendor/modernizr" %>
<%= javascript_include_tag 'application' %>
<%= yield :js %>

<% if Rails.env == 'production' %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-72309284-1', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

</body>
</html>